### ISSUE TITLE
ZPM fails in existing installation

### ISSUE THREAD

**Issue by r-cemper** [evshvarov/deployed-code-template#2]
USER>zpm "install deployed-oscript-template"

ERROR! Download module, hash mismatch. 4270ff4a00a046156a40bb9462f46a1202202c79
USER>zpm "ver"

%SYS> zpm 0.7.0
https://pm.community.intersystems.com - 1.0.6

**Comment by evshvarov** [comment]
thank you!
Looking into it

**Comment by r-cemper** [comment]
But load.... works  and both sources are visible 
USER>zpm "load /home/irisowner/dev/deployed-code/ -v"

Load started on 04/22/2024 16:42:48
Loading file /home/irisowner/dev/deployed-code/module.xml as xml
Imported document: deployed-oscript-template.ZPM
Load finished successfully.

Skipping preload - directory does not exist.
Load started on 04/22/2024 16:42:48
Loading file /home/irisowner/dev/deployed-code/module.xml as xml
Imported document: deployed-oscript-template.ZPM
Load finished successfully.

Loading deployed-oscript-template in process 800
[USER|deployed-oscript-template]        Reload START (/home/irisowner/dev/deployed-code/)
Skipping preload - directory does not exist.
Load of directory started on 04/22/2024 16:42:48 '*'

Loading file /home/irisowner/dev/deployed-code/src/dc/deployed/ObjectScript.cls as udl
Load finished successfully.

Load of directory started on 04/22/2024 16:42:48 '*'

Loading file /home/irisowner/dev/deployed-code/src/dc/withsource/ObjectScript.cls as udl
Load finished successfully.

[USER|deployed-oscript-template]        Reload SUCCESS
[deployed-oscript-template]     Module object refreshed.
[USER|deployed-oscript-template]        Validate START
[USER|deployed-oscript-template]        Validate SUCCESS
[USER|deployed-oscript-template]        Compile START
Compilation started on 04/22/2024 16:42:48 with qualifiers 'd-lck'
Compiling 2 classes
Compiling class dc.deployed.ObjectScript
Compiling class dc.withsource.ObjectScript
Compiling routine dc.deployed.ObjectScript.1
Compiling routine dc.withsource.ObjectScript.1
Compilation finished successfully in 0.016s.

[USER|deployed-oscript-template]        Compile SUCCESS
[USER|deployed-oscript-template]        Activate START
[USER|deployed-oscript-template]        Configure START
[USER|deployed-oscript-template]        Configure SUCCESS
Studio project created/updated: deployed-oscript-template.PRJ
[USER|deployed-oscript-template]        Activate SUCCESS

**Comment by r-cemper** [comment]
this is running in my mini-docker image
IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2024.1 (Build **262U**) Thu Mar 7 2024 15:36:40 EST

I try your complete package next

**Comment by evshvarov** [comment]
fixed

**Comment by r-cemper** [comment]
class stays with source until
**write $system.OBJ.MakeClassDeployed("dc.deployed.ObjectScript",,1)**

SO:  the Deploy param is ignored
&lt;Resource Name="dc.deployed.PKG" Deploy="true"/&gt;

**Comment by evshvarov** [comment]
USER>k text do
##class(%Compiler.UDL.TextServices).GetTextAsString($namespace,
"dc.deployed.ObjectScript", .text) w text

Class dc.deployed.ObjectScript

{


ClassMethod Test() As %Status

{

}


}

**Comment by r-cemper** [comment]
After clearing all docker caches and iris images it worked after restart.
versions look similar but all work as described. in all variants  ZPM install .. and ZPM load
Deployed is now really deployed.

**Comment by evshvarov** [comment]
Thank you, Robert!
